on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add other setup steps here: PHP setup, dependency installation, etc.

      - name: Print GraphQL Schema
        run: php artisan lighthouse:print-schema
