name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: aqa
          MYSQL_DATABASE: appointment_graphql_api
          MYSQL_USER: aqa
          MYSQL_PASSWORD: aqa
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, mysql
          coverage: none

      - name: Install MySQL Client
        run: sudo apt-get install -y mysql-client

      - name: Copy .env file
        run: cp .env.example.github .env

      - name: Copy .env testing file
        run: cp .env.testing.github .env.testing

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Generate key
        run: php artisan key:generate

      - name: Set Permissions
        run: chmod -R 777 bootstrap/cache

      - name: Clear GraphQL schema cache
        run: php artisan lighthouse:clear-cache

      - name: Output GraphQL Schema Files
        run: cat graphql/**/*.graphql

      - name: Print GraphQL Schema
        run: php artisan lighthouse:print-schema

      - name: Wait for MySQL
        run: until mysqladmin ping -h 127.0.0.1 -u root --password=passw0rd; do sleep 1; done

      - name: Migrate and Seed Database
        run: php artisan migrate --seed

      - name: Run Tests
        run: ./vendor/bin/pest
