name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

env:
  DB_HOST: 127.0.0.1

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: passw0rd
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Copy .env file
        run: cp .env.example.github .env

      - name: Copy .env testing file
        run: cp .env.testing.github .env.testing

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Storage Permission
        run: chmod -R 777 storage bootstrap/cache

      - name: Database Setup
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: laravel
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: passw0rd
        run: php artisan migrate:fresh --seed --force

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: laravel
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: passw0rd
        run: php artisan test
